"""empty message

Revision ID: 2f4ce6b346fc
Revises: 30b13ac296e8
Create Date: 2019-02-19 20:59:22.348809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4ce6b346fc'
down_revision = '30b13ac296e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('sampleId', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('accX', sa.Float(), nullable=True),
    sa.Column('accY', sa.Float(), nullable=True),
    sa.Column('accZ', sa.Float(), nullable=True),
    sa.Column('gyroX', sa.Float(), nullable=True),
    sa.Column('gyroY', sa.Float(), nullable=True),
    sa.Column('gyroZ', sa.Float(), nullable=True),
    sa.Column('magX', sa.Float(), nullable=True),
    sa.Column('magY', sa.Float(), nullable=True),
    sa.Column('magZ', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sampleId'),
    sa.UniqueConstraint('sampleId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
